language: python
python:
- '2.7'
services:
- mysql
before_script:
- mysql -e 'create database featurerequestapp_test'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: opsworks
  access_key_id: AKIAI4C2EEQQYY6PZ6YA
  secret_access_key:
    secure: XHwPLELQTYqASiX7YRavgOdJpgtg6W2Orv4sKwp4C27UNZzhGYMeCxHyQ0++GmNxGnsEsTCPbOM1u5LPjepwm4kn55TxbOHYFj0r/xQRJSyO0jGaib3QtE8nOrYG3n8VzpXKfh6GhD+wwilgWKLKP2DnQENB6gUjM7+/F7ATC9H86HZcs/dvPiUhRrsMWgTkzkHZhxv5mQcRMUqQGR0SEPTLSrtyp0Hr6iKLno22W2m1Fw3bGgo/A8OEpaolUAUjC/g8Yvix2Xyu8UQGMwkqcmeJiOj5o8KAjlesljqsSoiODlXBV1GQ2yViyCrr8w0UvYdgvqtJgojcXUx0A7bid3sIGqKT6Kzjicp7+IiTpu5MMbq7z94b/WYRWoy2Sn5/z9HpzQUj/sUBzyTJDT/9Ex3sI3q/SyWPxYhyjby+Nt0kEw11nJcheUkwGSBpRFy2ME6IHw38uhl0d9oT0gFz4EyWTQANpbc1I51eYVNv0+p7NokO3JnbwgcohwrqMx/yvXpfm/9K2LDHRmMyoI+e3GMb/Kg81xbHnTP81iPIioCYyJzKD5eEuaqZ+pwtUXvGBo4TmZNUKYr/xl6CbpOjNuF2lMINa1rQU/bR1zrKOMFBHR3c1uDVhflefhBUUTeU7WO0N6MJftHpmi//2v8kw8fzIxdEpSD7yIluse6s+hw=
  app-id: 4cf140f4-88ab-4655-a304-66a825a334ff
  on:
    repo: chandanadatta9/FeatureRequest
