language: python

python:
  - "2.7"

services:
  - mysql

before_script:
  - mysql -e 'create database featurerequestapp_test'

#install the required packages from the requirements.txt
install:
  - "pip install -r requirements.txt"

script:
  - nosetests